# Generated by Django 5.0.6 on 2024-05-28 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_group_remove_message_user_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.group'),
        ),
    ]
